version: "3.8"

services:
  backend:
    container_name: 'fast-commerce-backend'
    command: sh "docker/scripts/entrypoint.sh"
    tty: true
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    networks:
        - main
    depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_started
        smtp4dev:
            condition: service_started

  postgres:
    container_name: 'fast-commerce-postgres'
    image: postgres:15.4-alpine
    env_file:
      - ./backend/envs/pg.env
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

    networks:
      - main

  redis:
    container_name: 'fast-commerce-redis'
    image: redis:7-alpine
    expose:
      - "6379"
    volumes:
        - redis-data:/data
    networks:
      - main


  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: 'fast-commerce-smtp4dev'
    ports:
      - "5000:80"
    restart: always
    networks:
      - main

  celery:
    container_name: 'fast-commerce-celery'
    command: sh "docker/scripts/celery.sh"
    tty: true
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    volumes:
      - ./backend:/backend
    networks:
        - main
    depends_on:
      - backend
    env_file:
      - ./backend/envs/celery.env

networks:
    main:

volumes:
    postgres-data:
    redis-data:
