name: Test On Kubernetes
description: "Test the application on kubernetes"

runs:
  using: 'composite'
  steps:
    - uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'latest'

    - name: Create ConfigMap
      run: make confmap
      shell: bash

    - name: Run Kubernetes Deployments
      run: make k8s
      shell: bash

    - name: Wait for Test Database Deployments
      run: kubectl wait --for=condition=available --timeout=60s deployment/fast-commerce-database
      shell: bash

    - name: Wait for Redis Deployment
      run: kubectl wait --for=condition=available --timeout=60s deployment/fast-commerce-redis
      shell: bash

    - name: Wait for Backend Deployments
      run: kubectl wait --for=condition=available --timeout=60s deployment/fast-commerce-backend
      shell: bash

    - name: Run Backend Tests
      run: kubectl exec -it $(kubectl get pods | grep backend | awk '{print $1}') -- pytest
      shell: bash