apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
      app: fast-commerce-backend

spec:
    selector:
        app: fast-commerce-backend
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000
    type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-commerce-backend
  labels:
      app: fast-commerce-backend

spec:
    replicas: 1
    selector:
        matchLabels:
            app: fast-commerce-backend
    template:
        metadata:
            labels:
                app: fast-commerce-backend
        spec:
            containers:
              - name: fast-commerce-backend
                image: ml06py/fast_commerce:latest
                imagePullPolicy: Always
                ports:
                    - containerPort: 8000
                command: ["/bin/sh"]
                args: ["-c", "sh docker/scripts/prod-entrypoint.sh"]
                envFrom:
                  - configMapRef:
                      name: fast-commerce-env
                env:
                  - name: ENVIRONMENT
                    value: "PRODUCTION"