apiVersion: v1
kind: Service

metadata:
  name: fast-commerce-redis
  labels:
    app: fast-commerce-redis

spec:
    ports:
        - port: 6379
          targetPort: 6379
    selector:
        app: fast-commerce-redis

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: fast-commerce-redis
  labels:
    app: fast-commerce-redis

spec:
    replicas: 1
    selector:
        matchLabels:
          app: fast-commerce-redis
    template:
        metadata:
          labels:
              app: fast-commerce-redis
        spec:
          containers:
              - name: fast-commerce-redis
                image: redis:7-alpine
                ports:
                    - containerPort: 6379
                env:
                    - name: REDIS_URL
                      value: redis://redis:6379/0
                    - name: TEST_REDIS_URL
                      value: redis://redis-test:6379/0
