apiVersion: v1
kind: Service

metadata:
  name: fast-commerce-smtp4dev
  labels:
    app: fast-commerce-smtp4dev

spec:
    ports:
      - name : smtp
        port: 25
        targetPort: 25

      - name : panel
        port: 5000
        targetPort: 80

    selector:
        app: fast-commerce-smtp4dev

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: fast-commerce-smtp4dev
  labels:
    app: fast-commerce-smtp4dev

spec:
    replicas: 1
    selector:
        matchLabels:
          app: fast-commerce-smtp4dev
    template:
        metadata:
          labels:
              app: fast-commerce-smtp4dev
        spec:
          containers:
              - name: fast-commerce-smtp4dev
                image: rnwood/smtp4dev:v3
                ports:
                    - containerPort: 25
                    - containerPort: 80
                envFrom:
                  - configMapRef:
                      name: fast-commerce-env
