"""updated product rel 

Revision ID: a4cc793d6444
Revises: 144d484b88e8
Create Date: 2023-08-24 12:00:35.842017

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'a4cc793d6444'
down_revision: Union[str, None] = '144d484b88e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
