"""added lazy for rel

Revision ID: aeca497ca480
Revises: 4345d75aad2f
Create Date: 2023-08-23 17:45:06.615228

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'aeca497ca480'
down_revision: Union[str, None] = '4345d75aad2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
