"""added custom uuid field

Revision ID: afbb0cb5cc8d
Revises: faeb555b207a
Create Date: 2023-09-06 08:41:58.420877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afbb0cb5cc8d'
down_revision: Union[str, None] = 'faeb555b207a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
