name: Fast Commerce Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-on-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Images
      run: make build

    - name: Run Containers
      run: make run DETACHED=true

    - name: Run Backend Tests
      run: make test

  test-on-kubernetes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Start minikube
      uses: medyagh/setup-minikube@master


    - name: Create ConfigMap
      working-directory: backend/
      run: make confmap

    - name: Run Kubernetes Deployments
      run: kubectl apply -f kubernetes/

    - name: Wait for Database Deployments
      run: kubectl wait --for=condition=available --timeout=60s deployment/fast-commerce-database

    - name: Wait for Redis Service
      run: kubectl wait --for=condition=available --timeout=60s deployment/fast-commerce-redis

    - name: Wait for Backend Deployments
      run: kubectl wait --for=condition=available --timeout=60s deployment/fast-commerce-backend

    - name: Run Backend Tests
      run: kubectl exec -it $(kubectl get pods | grep backend | awk '{print $1}') -- pytest