name: Fast Commerce Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-test-with-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Images
      run: make build

    - name: Run Containers
      run: make run DETACHED=true

    - name: Run Backend Tests
      run: make test

  run-test-with-kubernetes:
    runs-on: ubuntu-latest
    needs: run-test-with-docker

    steps:
    - uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Start minikube
      uses: medyagh/setup-minikube@master


    - name: Create ConfigMap
      run: kubectl create configmap fast-commerce-env --from-env-file=backend/envs/cache.env --from-env-file=backend/envs/celery.env --from-env-file=backend/envs/jwt.env --from-env-file=backend/envs/mail.env --from-env-file=backend/envs/pg.env --from-env-file=backend/envs/redis.env

    - name: Run Kubernetes Deployments
      run: kubectl apply -f kubernetes/

    - name: Wait for Deployments
      run: kubectl wait --for=condition=available --timeout=600s deployment/fast-commerce-backend

    - name: Run Backend Tests
      run: kubectl exec -it $(kubectl get pods | grep backend | awk '{print $1}') -- pytest